### ISSUE TITLE
source of lat/long for location objects

### ISSUE THREAD

**Issue by bl-young** [GreenDelta/data#19]
the lat long data in the [locations refdata](https://github.com/GreenDelta/data/blob/master/refdata/locations.csv) does not align with the lat/long on the location objects in openLCA 2.2. It looks like instead they are coming from elsewhere, e.g., perhaps the [geoJSON files from ecoinvent](https://geography.ecoinvent.org/#data-formats). can you confirm?

I'd like to recreate these and want to make sure I am aligning with what is done in openLCA, is there an existing process for creating the ref location objects?

**Comment by msrocka** [comment]
When building the reference database that is packaged with openLCA, it first imports the CSV file from this repository and then it imports and updates locations with the ecoinvent geographies. It matches them by their location codes, if a matching ecoinvent geography has a longitude and latitude defined, it will replace the coordinates from the CSV file with that information from ecoinvent.
