### ISSUE TITLE
wrong number

### ISSUE THREAD

**Issue by tlohse** [GreenDelta/data#3]
Nitrogen dioxide,Emission to air/low population density,Mass,7.63E-08,species.yr/kg,none
is wrong

**Comment by tlohse** [comment]
#2  was also wrong

**Comment by salwaburhan** [comment]
modified here : https://github.com/GreenDelta/data/commit/634e8cb6de705b781e1d90f497ff905c9418a84f

**Comment by salwaburhan** [comment]
https://greendelta.github.io/data/ issue in blah blah

**Comment by salwaburhan** [comment]
here pasted: https://github.com/GreenDelta/data/commit/634e8cb6de705b781e1d90f497ff905c9418a84f

**Comment by tlohse** [comment]
issue has been fixed, CF is updated
